controller_manager_ns: controller_manager
controller_list:
  - name: sara_arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_shoulder_roll_joint
      - right_shoulder_pitch_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_elbow_yaw_joint
      - right_wrist_pitch_joint
      - right_wrist_roll_joint
  -
    name: sara_gripper_action_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - right_finger_joint
