controller_list:
  - name: fake_RightArm_controller
    joints:
      - base_actuator_joint
      - right_shoulder_roll_joint
      - right_shoulder_pitch_joint
      - right_shoulder_yaw_joint
      - right_elbow_pitch_joint
      - right_elbow_yaw_joint
      - right_wrist_pitch_joint
      - right_wrist_roll_joint
  - name: fake_RightGripper_controller
    joints:
      - right_finger_joint