move_group:
  controller_manager_ns: controller_manager
  controller_list:
    - name: sara_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - front_actuator_joint
        - right_shoulder_roll_joint
        - right_shoulder_pitch_joint
        - right_shoulder_yaw_joint
        - right_elbow_pitch_joint
        - right_elbow_yaw_joint
        - right_wrist_pitch_joint
        - right_wrist_roll_joint
    - name: sara_gripper_action_controller
      action_ns: gripper_cmd
      default: True
      type: GripperCommand
      joints:
        - gripper_finger1_joint
