 sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /head_xtion/depth/points
    max_range: 5.0
    frame_subsample: 1
    point_subsample: 1
    self_mask:
        min_sensor_dist: .8
        self_see_default_padding: .04
        self_see_default_scale: 1.0
        self_see_links:
            - name: right_clavicular_link
              padding: 0.05
            - name: right_upper_arm_upper_link
              padding: 0.05
            - name: right_upper_arm_lower_link
              padding: 0.05
            - name: right_forearm_upper_link
              padding: 0.05
            - name: right_forearm_lower_link
              padding: 0.05
            - name: right_wrist_upper_link
              padding: 0.05
            - name: right_wrist_lower_link
              padding: 0.05
            - name: right_socket_link
              padding: 0.05
            - name: right_robotiq_85_base_link
              padding: 0.05
            - name: right_robotiq_85_left_knuckle_link
              padding: 0.05
            - name: right_robotiq_85_right_knuckle_link
              padding: 0.05
            - name: right_robotiq_85_left_finger_link
              padding: 0.05
            - name: right_robotiq_85_right_finger_link
              padding: 0.05
            - name: right_robotiq_85_left_inner_knuckle_link
              padding: 0.05
            - name: right_robotiq_85_right_inner_knuckle_link
              padding: 0.05
            - name: right_robotiq_85_left_finger_tip_link
              padding: 0.05
            - name: right_robotiq_85_right_finger_tip_link
              padding: 0.05